{% set name = "torchmanager" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/40/73/6f0ff5c85c63eb7734b4c79623103c0e05a6a18c35be954420148a613e3b/torchmanager-1.3.3.tar.gz
  sha256: 08425f7fe3b23dea6d89680e784cbaafede0f244cf461e7d0e8fb0f2af243e2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - packaging >=16.8
    - pytorch
    - tqdm

test:
  imports:
    - torchmanager
    - torchmanager_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kisonho/torchmanager.git
  summary: PyTorch Training Manager v1.3.3
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kisonho
