{% set name = "torchmanager" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/torchmanager-1.3.3.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install {{ SRC_DIR }}/torchmanager-1.3.3.tar.gz -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - packaging >=16.8
    - pytorch
    - tqdm

test:
  imports:
    - torchmanager
    - torchmanager_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kisonho/torchmanager.git
  summary: PyTorch Training Manager v1.3.3
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kisonho
