{% set name = "torchmanager" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4e/29/211bbfe52403c2d65f36a8bc76dad6484ed3f7af474f8fef87025879fd6f/torchmanager-1.2.5.tar.gz
  sha256: edb6b2063968d1a740b6a0bc591242986c141f06ed582ff176035ac77786c955

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pytorch
    - tqdm

test:
  imports:
    - torchmanager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kisonho/torchmanager.git
  summary: PyTorch Training Manager v1.2.5
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kisonho
